# Generated by Django 4.2.6 on 2023-11-07 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submit_request", "0021_saasrequest_certification_saasrequest_google_sign_in"),
        ("user", "0005_users_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_center", models.CharField(max_length=100)),
                ("travel_living_costs", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                (
                    "date_submitted",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date submitted"
                    ),
                ),
                ("date_manager_reviewed", models.DateTimeField(blank=True, null=True)),
                ("date_s32_reviewed", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_manager",
                        to="user.users",
                        verbose_name="training_manager",
                    ),
                ),
                (
                    "s32_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_approved_by",
                        to="user.users",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("duration", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submit_request.currency",
                    ),
                ),
            ],
        ),
    ]
