# Generated by Django 4.2.6 on 2023-11-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("internal_ops", "0002_alter_fundcenter_name_alter_fundcenter_number"),
        ("training_request", "0002_trainingrequest_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequest",
            name="fund_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="internal_ops.fundcenter",
            ),
        ),
    ]
