# Generated by Django 4.2.6 on 2023-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_request", "0003_alter_trainingrequest_fund_center"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
