# Generated by Django 4.1.7 on 2023-03-06 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0002_saasrequest_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="date_submitted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
