# Generated by Django 4.1.7 on 2023-03-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0003_saasrequest_approved_saasrequest_date_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="date_reviewed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="denied",
            field=models.BooleanField(default=False),
        ),
    ]
