# Generated by Django 4.1.7 on 2023-03-10 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submit_request", "0005_saasrequest_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
