# Generated by Django 4.1.7 on 2023-03-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0006_alter_saasrequest_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="date_reviewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
