# Generated by Django 4.1.7 on 2023-03-13 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0007_alter_saasrequest_date_reviewed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saasrequest",
            old_name="approver",
            new_name="manager",
        ),
    ]
