# Generated by Django 4.1.7 on 2023-03-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("internal_ops", "0001_initial"),
        ("submit_request", "0010_saasrequest_date_sent_to_s_32_approver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="fund_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="internal_ops.fundcenter",
            ),
        ),
    ]
