# Generated by Django 4.1.7 on 2023-03-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0011_saasrequest_fund_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
