# Generated by Django 4.1.7 on 2023-03-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_users_roles_users_user_roles"),
        ("submit_request", "0012_saasrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_by",
                to="user.users",
            ),
        ),
    ]
