# Generated by Django 4.1.7 on 2023-03-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_users_roles_users_user_roles"),
        ("submit_request", "0013_alter_saasrequest_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="internal_ops",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_ops",
                to="user.users",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saasrequest",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager",
                to="user.users",
            ),
        ),
    ]
