# Generated by Django 4.1.7 on 2023-03-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0016_saasrequest_confirmation_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="purchase_notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
