# Generated by Django 4.2 on 2023-05-09 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0018_saasrequest_info_requested_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saasrequest",
            old_name="purchse_amount",
            new_name="purchase_amount",
        ),
    ]
