# Generated by Django 4.2.2 on 2023-06-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0019_rename_purchse_amount_saasrequest_purchase_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="currency")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(max_length=100, verbose_name="frequency"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="duration",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="duration"
            ),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="units",
            field=models.IntegerField(blank=True, null=True, verbose_name="units"),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_currency",
                to="submit_request.currency",
            ),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_frequency",
                to="submit_request.frequency",
            ),
        ),
    ]
