# Generated by Django 4.2.2 on 2023-06-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0019_rename_purchse_amount_saasrequest_purchase_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="currency")),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(max_length=100, verbose_name="frequency"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="comments",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="duration",
            field=models.CharField(default=1, max_length=100, verbose_name="duration"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="units",
            field=models.IntegerField(default=1, verbose_name="units"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="submit_request.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="frequency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="submit_request.frequency",
            ),
            preserve_default=False,
        ),
    ]
