# Generated by Django 4.2.4 on 2023-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0020_currency_frequency_saasrequest_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saasrequest",
            name="certification",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="saasrequest",
            name="google_sign_in",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
