# Generated by Django 4.2.2 on 2023-06-14 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0020_currency_frequency_saasrequest_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submit_request.currency",
                verbose_name="currency",
            ),
        ),
        migrations.AlterField(
            model_name="saasrequest",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="submit_request.frequency",
                verbose_name="frequency",
            ),
        ),
    ]
