# Generated by Django 4.2.2 on 2023-06-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0021_alter_saasrequest_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="description",
            field=models.CharField(
                default=1, max_length=500, verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frequency",
            name="description",
            field=models.CharField(
                default=1, max_length=500, verbose_name="description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saasrequest",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_currency",
                to="submit_request.currency",
            ),
        ),
        migrations.AlterField(
            model_name="saasrequest",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_frequency",
                to="submit_request.frequency",
            ),
        ),
    ]
