# Generated by Django 4.2.2 on 2023-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0022_currency_description_frequency_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
