# Generated by Django 4.2.2 on 2023-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("submit_request", "0023_alter_saasrequest_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saasrequest",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default="CDN",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_currency",
                to="submit_request.currency",
            ),
        ),
        migrations.AlterField(
            model_name="saasrequest",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saas_frequency",
                to="submit_request.frequency",
            ),
        ),
    ]
