version: '3.4'
services:
  saas_app:
    image: saas
    build:
      context: ../saas_app
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:cached
    environment:
      - POSTGRES_DB=saas
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - DB_HOST=postgresdb
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:14.6@sha256:2481115cad236897774fa13fef07ceb0e5fdc0a75457a047c441aada670cdfaf
    volumes:
       - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=saas
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    expose:
      - 5432
