# Generated by Django 4.1.7 on 2023-03-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="roles",
        ),
        migrations.AddField(
            model_name="users",
            name="user_roles",
            field=models.ManyToManyField(to="user.roles"),
        ),
    ]
