# Generated by Django 4.2.2 on 2023-06-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_roles_description_alter_roles_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="business_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
