# Generated by Django 4.2.6 on 2023-11-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_users_business_unit_alter_users_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
