# Generated by Django 4.2.7 on 2023-12-07 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_users_dept_email_users_employment_status_users_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="employment_status",
            new_name="city",
        ),
    ]
