# Generated by Django 4.2.3 on 2023-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleWorkspaceAppsLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_generated", models.DateTimeField()),
                ("source_system", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("application_name", models.CharField(max_length=100)),
                ("user_email", models.CharField(max_length=100)),
                ("user_ip_address", models.CharField(max_length=100)),
                ("event_name", models.CharField(max_length=100)),
                ("client_id", models.CharField(max_length=100)),
                ("application_name_id", models.CharField(max_length=100)),
                ("client_type", models.CharField(max_length=100)),
                ("scope_data", models.CharField(max_length=1000)),
                ("scope", models.CharField(max_length=1000)),
                ("geolocation_country", models.CharField(max_length=100)),
                ("geolocation_city", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
    ]
