# Generated by Django 4.2.3 on 2023-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manage_saas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleworkspaceappslogin",
            name="scope",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="googleworkspaceappslogin",
            name="scope_data",
            field=models.CharField(),
        ),
    ]
