# Generated by Django 4.2 on 2023-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="number",
            field=models.CharField(max_length=100, verbose_name="number"),
        ),
    ]
