version: '3.4'

services:
  saas_app:
    image: saas
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=saas
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev