name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - saas_app/**
      - .github/workflows/ci_code.yml

env:
  TERRAGRUNT_VERSION: v0.31.1

jobs:
  lint-fmt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        working-directory: ./saas_app
        run: make install-dev

      - name: Install dependencies
        working-directory: ./saas_app
        run: make install

      - name: Lint
        working-directory: ./saas_app
        run: make lint-ci

      - name: Format
        working-directory: ./saas_app
        run: make fmt-ci

      - name: Test
        working-directory: ./saas_app
        run: make test
