name: Docker build

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # tag=v2.11.1
        id: filter
        with:
          filters: |
            saas_app: 'saas_app/**'
  build:
    if: needs.changes.outputs.images != '[]'
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.changes.outputs.images) }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M:%S')"

      - name: Build image
        working-directory: ./${{ matrix.image }}
        run: |
          docker build \
          -t ${{ matrix.image }}:latest \
          --build-arg GIT_SHA=${{ github.sha }} \
          --build-arg BUILD_DATE=${{ steps.date.outputs.date }} .

      - name: Dive into image
        uses: cds-snc/dive-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ matrix.image }}:latest
