name: "Terraform apply"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply.yml"

env:
  TERRAFORM_VERSION: 1.6.2
  TERRAGRUNT_VERSION: 0.52.4
  AWS_REGION: ca-central-1
  TF_VAR_database_password: ${{ secrets.POSTGRES_PASSWORD }}
  TF_VAR_database_username: ${{ secrets.POSTGRES_USER }}
  TF_VAR_database_name: ${{ secrets.POSTGRES_DB }}
  TF_VAR_saas_app_config: ${{ secrets.APP_CONFIG }}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}


permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1.7.0
        with:
          role-to-assume: arn:aws:iam::394954348146:role/gh_admin_role
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply ssm
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply iam
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply hosted_zone
        working-directory: terragrunt/env/staging/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply network
        working-directory: terragrunt/env/staging/network
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply load_balancer 
        working-directory: terragrunt/env/staging/load_balancer
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply ecr 
        working-directory: terragrunt/env/staging/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply rds
        working-directory: terragrunt/env/staging/rds
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply ecs 
        working-directory: terragrunt/env/staging/ecs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
