name: "Terraform apply"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_apply.yml"

env:
  TERRAFORM_VERSION: 1.3.7
  TERRAGRUNT_VERSION: 0.40.2
  AWS_REGION: ca-central-1
  TF_VAR_database_password: ${{ secrets.POSTGRES_PASSWORD }}
  TF_VAR_database_username: ${{ secrets.POSTGRES_USER }}
  TF_VAR_database_name: ${{ secrets.POSTGRES_DB }}


permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1.7.0
        with:
          role-to-assume: arn:aws:iam::394954348146:role/gh_admin_role
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply ssm
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply iam
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply hosted_zone
        working-directory: terragrunt/env/staging/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply network
        working-directory: terragrunt/env/staging/network
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply load_balancer 
        working-directory: terragrunt/env/staging/load_balancer
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply ecr 
        working-directory: terragrunt/env/staging/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply ecs 
        working-directory: terragrunt/env/staging/ecs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
      
      - name: Apply rds 
        working-directory: terragrunt/env/staging/rds
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
